FROM alpine:3.22.1 AS sdk

WORKDIR "/root/code/wyvern"

RUN apk update
RUN apk add --no-cache \
    bash \
    git \
    openssh \
    curl \
    zlib-dev \
    g++ \
    ghc \
    cabal \
    ncurses-dev

RUN git config --global --add safe.directory "/root/code/wyvern"

RUN echo 'export PS1="\[\e[32m\]\w\[\e[35m\]\$\[\e[0m\] "' >> /root/.bashrc

# 2024-12-02 PJ:
# --------------
# this is where executables
# installed with cabal install are located
ENV PATH="${PATH}:/root/.local/bin"

COPY ./setup-cabal.sh /root/code/wyvern/

COPY ./build-code.sh /root/code/wyvern/

COPY Wyvern.cabal /root/code/wyvern/

COPY ./app /root/code/wyvern/app/

COPY ./lib /root/code/wyvern/lib/

RUN /root/code/wyvern/setup-cabal.sh

RUN /root/code/wyvern/build-code.sh

RUN find /root/code/wyvern/dist-newstyle -name Wyvern -type f -exec cp {} /tmp/ \;

FROM alpine:3.22.1

RUN apk update
RUN apk add --no-cache \
    libgmpxx \
    libffi

RUN addgroup -S appgroup && adduser -S runtime -G appgroup -D

COPY --from=sdk /tmp/Wyvern /usr/local/bin/

USER runtime

ENTRYPOINT [ "/usr/local/bin/Wyvern" ]

CMD [ "--help" ]
