FROM alpine:3.22.1

ARG CODE_DIR="/root/code/wyvern/"

WORKDIR "$CODE_DIR"

RUN apk update
RUN apk add \
    bash \
    git \
    openssh \
    curl \
    zlib-dev \
    g++ \
    ghc \
    cabal \
    ncurses-dev
RUN git config --global --add safe.directory "$CODE_DIR"

RUN echo 'export PS1="\[\e[32m\]\w\[\e[35m\]\$\[\e[0m\] "' >> /root/.bashrc

# 2024-12-02 PJ:
# --------------
# this is where executables
# installed with cabal install are located
ENV PATH="${PATH}:/root/.local/bin"

COPY setup-cabal.sh "$CODE_DIR"

COPY Wyvern.cabal "$CODE_DIR"

RUN "$CODE_DIR"setup-cabal.sh && cabal build --enable-executable-stripping
