FROM alpine:3.22.1 AS sdk

WORKDIR "/root/code/wyvern"

RUN apk update
RUN apk add --no-cache \
    bash \
    git \
    openssh \
    curl \
    zlib-dev \
    g++ \
    ghc \
    cabal \
    ncurses-dev

RUN git config --global --add safe.directory "/root/code/wyvern"

RUN echo 'export PS1="\[\e[32m\]\w\[\e[35m\]\$\[\e[0m\] "' >> /root/.bashrc

ENV PATH="${PATH}:/root/.local/bin"

COPY ./wyvern.cabal /root/code/wyvern/

COPY ./src /root/code/wyvern/src/

RUN cabal update

RUN cabal build --enable-executable-stripping

RUN find /root/code/wyvern/dist-newstyle -name wyvern -type f -exec cp {} /tmp/ \;

FROM alpine:3.22.1

RUN apk update
RUN apk add --no-cache \
    libgmpxx \
    libffi

RUN addgroup -S appgroup && adduser -S runtime -G appgroup -D

COPY --from=sdk /tmp/wyvern /usr/local/bin/

USER runtime

ENTRYPOINT [ "/usr/local/bin/wyvern" ]

CMD [ "--help" ]
